//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS2_Console_Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS2_Console_Client.ServiceReference.Offer[] offerListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPasswordField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        private System.DateTime Created_atField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WS2_Console_Client.ServiceReference.Offer[] offerList {
            get {
                return this.offerListField;
            }
            set {
                if ((object.ReferenceEquals(this.offerListField, value) != true)) {
                    this.offerListField = value;
                    this.RaisePropertyChanged("offerList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HashedPassword {
            get {
                return this.HashedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPasswordField, value) != true)) {
                    this.HashedPasswordField = value;
                    this.RaisePropertyChanged("HashedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Created_at {
            get {
                return this.Created_atField;
            }
            set {
                if ((this.Created_atField.Equals(value) != true)) {
                    this.Created_atField = value;
                    this.RaisePropertyChanged("Created_at");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Offer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private int StampGoalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS2_Console_Client.ServiceReference.Store StoreField;
        
        private System.DateTime Created_atField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StampGoal {
            get {
                return this.StampGoalField;
            }
            set {
                if ((this.StampGoalField.Equals(value) != true)) {
                    this.StampGoalField = value;
                    this.RaisePropertyChanged("StampGoal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WS2_Console_Client.ServiceReference.Store Store {
            get {
                return this.StoreField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreField, value) != true)) {
                    this.StoreField = value;
                    this.RaisePropertyChanged("Store");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Created_at {
            get {
                return this.Created_atField;
            }
            set {
                if ((this.Created_atField.Equals(value) != true)) {
                    this.Created_atField = value;
                    this.RaisePropertyChanged("Created_at");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Store", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Store : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private System.DateTime Created_atField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Created_at {
            get {
                return this.Created_atField;
            }
            set {
                if ((this.Created_atField.Equals(value) != true)) {
                    this.Created_atField = value;
                    this.RaisePropertyChanged("Created_at");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subscription", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Subscription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int customer_IdField;
        
        private int offer_IdField;
        
        private int stamps_attainedField;
        
        private System.DateTime created_atField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int customer_Id {
            get {
                return this.customer_IdField;
            }
            set {
                if ((this.customer_IdField.Equals(value) != true)) {
                    this.customer_IdField = value;
                    this.RaisePropertyChanged("customer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int offer_Id {
            get {
                return this.offer_IdField;
            }
            set {
                if ((this.offer_IdField.Equals(value) != true)) {
                    this.offer_IdField = value;
                    this.RaisePropertyChanged("offer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stamps_attained {
            get {
                return this.stamps_attainedField;
            }
            set {
                if ((this.stamps_attainedField.Equals(value) != true)) {
                    this.stamps_attainedField = value;
                    this.RaisePropertyChanged("stamps_attained");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime created_at {
            get {
                return this.created_atField;
            }
            set {
                if ((this.created_atField.Equals(value) != true)) {
                    this.created_atField = value;
                    this.RaisePropertyChanged("created_at");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.GetEntitiesSoap")]
    public interface GetEntitiesSoap {
        
        // CODEGEN: Generating message contract since element name GetCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        WS2_Console_Client.ServiceReference.GetCustomersResponse GetCustomers(WS2_Console_Client.ServiceReference.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetCustomersResponse> GetCustomersAsync(WS2_Console_Client.ServiceReference.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name GetStoresResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStores", ReplyAction="*")]
        WS2_Console_Client.ServiceReference.GetStoresResponse GetStores(WS2_Console_Client.ServiceReference.GetStoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStores", ReplyAction="*")]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetStoresResponse> GetStoresAsync(WS2_Console_Client.ServiceReference.GetStoresRequest request);
        
        // CODEGEN: Generating message contract since element name GetOffersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffers", ReplyAction="*")]
        WS2_Console_Client.ServiceReference.GetOffersResponse GetOffers(WS2_Console_Client.ServiceReference.GetOffersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffers", ReplyAction="*")]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetOffersResponse> GetOffersAsync(WS2_Console_Client.ServiceReference.GetOffersRequest request);
        
        // CODEGEN: Generating message contract since element name GetSubscriptionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubscriptions", ReplyAction="*")]
        WS2_Console_Client.ServiceReference.GetSubscriptionsResponse GetSubscriptions(WS2_Console_Client.ServiceReference.GetSubscriptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubscriptions", ReplyAction="*")]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetSubscriptionsResponse> GetSubscriptionsAsync(WS2_Console_Client.ServiceReference.GetSubscriptionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetCustomersRequestBody Body;
        
        public GetCustomersRequest() {
        }
        
        public GetCustomersRequest(WS2_Console_Client.ServiceReference.GetCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomersRequestBody {
        
        public GetCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetCustomersResponseBody Body;
        
        public GetCustomersResponse() {
        }
        
        public GetCustomersResponse(WS2_Console_Client.ServiceReference.GetCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS2_Console_Client.ServiceReference.Customer[] GetCustomersResult;
        
        public GetCustomersResponseBody() {
        }
        
        public GetCustomersResponseBody(WS2_Console_Client.ServiceReference.Customer[] GetCustomersResult) {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStores", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetStoresRequestBody Body;
        
        public GetStoresRequest() {
        }
        
        public GetStoresRequest(WS2_Console_Client.ServiceReference.GetStoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStoresRequestBody {
        
        public GetStoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetStoresResponseBody Body;
        
        public GetStoresResponse() {
        }
        
        public GetStoresResponse(WS2_Console_Client.ServiceReference.GetStoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS2_Console_Client.ServiceReference.Store[] GetStoresResult;
        
        public GetStoresResponseBody() {
        }
        
        public GetStoresResponseBody(WS2_Console_Client.ServiceReference.Store[] GetStoresResult) {
            this.GetStoresResult = GetStoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOffersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOffers", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetOffersRequestBody Body;
        
        public GetOffersRequest() {
        }
        
        public GetOffersRequest(WS2_Console_Client.ServiceReference.GetOffersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOffersRequestBody {
        
        public GetOffersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOffersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOffersResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetOffersResponseBody Body;
        
        public GetOffersResponse() {
        }
        
        public GetOffersResponse(WS2_Console_Client.ServiceReference.GetOffersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOffersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS2_Console_Client.ServiceReference.Offer[] GetOffersResult;
        
        public GetOffersResponseBody() {
        }
        
        public GetOffersResponseBody(WS2_Console_Client.ServiceReference.Offer[] GetOffersResult) {
            this.GetOffersResult = GetOffersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubscriptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubscriptions", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetSubscriptionsRequestBody Body;
        
        public GetSubscriptionsRequest() {
        }
        
        public GetSubscriptionsRequest(WS2_Console_Client.ServiceReference.GetSubscriptionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSubscriptionsRequestBody {
        
        public GetSubscriptionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubscriptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubscriptionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS2_Console_Client.ServiceReference.GetSubscriptionsResponseBody Body;
        
        public GetSubscriptionsResponse() {
        }
        
        public GetSubscriptionsResponse(WS2_Console_Client.ServiceReference.GetSubscriptionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubscriptionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS2_Console_Client.ServiceReference.Subscription[] GetSubscriptionsResult;
        
        public GetSubscriptionsResponseBody() {
        }
        
        public GetSubscriptionsResponseBody(WS2_Console_Client.ServiceReference.Subscription[] GetSubscriptionsResult) {
            this.GetSubscriptionsResult = GetSubscriptionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetEntitiesSoapChannel : WS2_Console_Client.ServiceReference.GetEntitiesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntitiesSoapClient : System.ServiceModel.ClientBase<WS2_Console_Client.ServiceReference.GetEntitiesSoap>, WS2_Console_Client.ServiceReference.GetEntitiesSoap {
        
        public GetEntitiesSoapClient() {
        }
        
        public GetEntitiesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetEntitiesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEntitiesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetEntitiesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS2_Console_Client.ServiceReference.GetCustomersResponse WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetCustomers(WS2_Console_Client.ServiceReference.GetCustomersRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public WS2_Console_Client.ServiceReference.Customer[] GetCustomers() {
            WS2_Console_Client.ServiceReference.GetCustomersRequest inValue = new WS2_Console_Client.ServiceReference.GetCustomersRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetCustomersRequestBody();
            WS2_Console_Client.ServiceReference.GetCustomersResponse retVal = ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetCustomersResponse> WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetCustomersAsync(WS2_Console_Client.ServiceReference.GetCustomersRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetCustomersResponse> GetCustomersAsync() {
            WS2_Console_Client.ServiceReference.GetCustomersRequest inValue = new WS2_Console_Client.ServiceReference.GetCustomersRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetCustomersRequestBody();
            return ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS2_Console_Client.ServiceReference.GetStoresResponse WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetStores(WS2_Console_Client.ServiceReference.GetStoresRequest request) {
            return base.Channel.GetStores(request);
        }
        
        public WS2_Console_Client.ServiceReference.Store[] GetStores() {
            WS2_Console_Client.ServiceReference.GetStoresRequest inValue = new WS2_Console_Client.ServiceReference.GetStoresRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetStoresRequestBody();
            WS2_Console_Client.ServiceReference.GetStoresResponse retVal = ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetStores(inValue);
            return retVal.Body.GetStoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetStoresResponse> WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetStoresAsync(WS2_Console_Client.ServiceReference.GetStoresRequest request) {
            return base.Channel.GetStoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetStoresResponse> GetStoresAsync() {
            WS2_Console_Client.ServiceReference.GetStoresRequest inValue = new WS2_Console_Client.ServiceReference.GetStoresRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetStoresRequestBody();
            return ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetStoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS2_Console_Client.ServiceReference.GetOffersResponse WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetOffers(WS2_Console_Client.ServiceReference.GetOffersRequest request) {
            return base.Channel.GetOffers(request);
        }
        
        public WS2_Console_Client.ServiceReference.Offer[] GetOffers() {
            WS2_Console_Client.ServiceReference.GetOffersRequest inValue = new WS2_Console_Client.ServiceReference.GetOffersRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetOffersRequestBody();
            WS2_Console_Client.ServiceReference.GetOffersResponse retVal = ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetOffers(inValue);
            return retVal.Body.GetOffersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetOffersResponse> WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetOffersAsync(WS2_Console_Client.ServiceReference.GetOffersRequest request) {
            return base.Channel.GetOffersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetOffersResponse> GetOffersAsync() {
            WS2_Console_Client.ServiceReference.GetOffersRequest inValue = new WS2_Console_Client.ServiceReference.GetOffersRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetOffersRequestBody();
            return ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetOffersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS2_Console_Client.ServiceReference.GetSubscriptionsResponse WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetSubscriptions(WS2_Console_Client.ServiceReference.GetSubscriptionsRequest request) {
            return base.Channel.GetSubscriptions(request);
        }
        
        public WS2_Console_Client.ServiceReference.Subscription[] GetSubscriptions() {
            WS2_Console_Client.ServiceReference.GetSubscriptionsRequest inValue = new WS2_Console_Client.ServiceReference.GetSubscriptionsRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetSubscriptionsRequestBody();
            WS2_Console_Client.ServiceReference.GetSubscriptionsResponse retVal = ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetSubscriptions(inValue);
            return retVal.Body.GetSubscriptionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetSubscriptionsResponse> WS2_Console_Client.ServiceReference.GetEntitiesSoap.GetSubscriptionsAsync(WS2_Console_Client.ServiceReference.GetSubscriptionsRequest request) {
            return base.Channel.GetSubscriptionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS2_Console_Client.ServiceReference.GetSubscriptionsResponse> GetSubscriptionsAsync() {
            WS2_Console_Client.ServiceReference.GetSubscriptionsRequest inValue = new WS2_Console_Client.ServiceReference.GetSubscriptionsRequest();
            inValue.Body = new WS2_Console_Client.ServiceReference.GetSubscriptionsRequestBody();
            return ((WS2_Console_Client.ServiceReference.GetEntitiesSoap)(this)).GetSubscriptionsAsync(inValue);
        }
    }
}
