//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_WindowsForms_Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relative", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Relative : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelativeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.DateTime BirthDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RelativeCode {
            get {
                return this.RelativeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RelativeCodeField, value) != true)) {
                    this.RelativeCodeField = value;
                    this.RaisePropertyChanged("RelativeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetadataItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MetadataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstraintNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstraintTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexTypeField;
        
        private bool IsUniqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ConstraintName {
            get {
                return this.ConstraintNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstraintNameField, value) != true)) {
                    this.ConstraintNameField = value;
                    this.RaisePropertyChanged("ConstraintName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ConstraintType {
            get {
                return this.ConstraintTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstraintTypeField, value) != true)) {
                    this.ConstraintTypeField = value;
                    this.RaisePropertyChanged("ConstraintType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IndexName {
            get {
                return this.IndexNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexNameField, value) != true)) {
                    this.IndexNameField = value;
                    this.RaisePropertyChanged("IndexName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IndexType {
            get {
                return this.IndexTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexTypeField, value) != true)) {
                    this.IndexTypeField = value;
                    this.RaisePropertyChanged("IndexType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsUnique {
            get {
                return this.IsUniqueField;
            }
            set {
                if ((this.IsUniqueField.Equals(value) != true)) {
                    this.IsUniqueField = value;
                    this.RaisePropertyChanged("IsUnique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.CronusSoap")]
    public interface CronusSoap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse GetEmployees(ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse> GetEmployeesAsync(ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse RemoveEmployee(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse> RemoveEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name emp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse CreateEmployee(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse> CreateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSickEmployeesByYear", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse GetSickEmployeesByYear(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSickEmployeesByYear", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse> GetSickEmployeesByYearAsync(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest request);
        
        // CODEGEN: Generating message contract since element name empNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRelatives", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse GetRelatives(ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse> GetRelativesAsync(ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name emp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse UpdateEmployee(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse> UpdateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnNames", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse GetColumnNames(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetColumnNames", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse> GetColumnNamesAsync(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest request);
        
        // CODEGEN: Generating message contract since element name GetTableNamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableNames", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse GetTableNames(ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableNames", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse> GetTableNamesAsync(ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse GetIndexes(ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse> GetIndexesAsync(ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConstraints", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse GetConstraints(ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse> GetConstraintsAsync(ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeNameMostAbsenceResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeNameMostAbsence", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse GetEmployeeNameMostAbsence(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeNameMostAbsence", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse> GetEmployeeNameMostAbsenceAsync(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest request);
        
        // CODEGEN: Generating message contract since element name tableName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableContent", ReplyAction="*")]
        ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse GetTableContent(ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableContent", ReplyAction="*")]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse> GetTableContentAsync(ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.Employee[] GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(ERP_WindowsForms_Client.ServiceReference.Employee[] GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequestBody Body;
        
        public RemoveEmployeeRequest() {
        }
        
        public RemoveEmployeeRequest(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public RemoveEmployeeRequestBody() {
        }
        
        public RemoveEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponseBody Body;
        
        public RemoveEmployeeResponse() {
        }
        
        public RemoveEmployeeResponse(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RemoveEmployeeResult;
        
        public RemoveEmployeeResponseBody() {
        }
        
        public RemoveEmployeeResponseBody(bool RemoveEmployeeResult) {
            this.RemoveEmployeeResult = RemoveEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.Employee emp;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(bool CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSickEmployeesByYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSickEmployeesByYear", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequestBody Body;
        
        public GetSickEmployeesByYearRequest() {
        }
        
        public GetSickEmployeesByYearRequest(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSickEmployeesByYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public GetSickEmployeesByYearRequestBody() {
        }
        
        public GetSickEmployeesByYearRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSickEmployeesByYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSickEmployeesByYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponseBody Body;
        
        public GetSickEmployeesByYearResponse() {
        }
        
        public GetSickEmployeesByYearResponse(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSickEmployeesByYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.Employee[] GetSickEmployeesByYearResult;
        
        public GetSickEmployeesByYearResponseBody() {
        }
        
        public GetSickEmployeesByYearResponseBody(ERP_WindowsForms_Client.ServiceReference.Employee[] GetSickEmployeesByYearResult) {
            this.GetSickEmployeesByYearResult = GetSickEmployeesByYearResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelatives", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetRelativesRequestBody Body;
        
        public GetRelativesRequest() {
        }
        
        public GetRelativesRequest(ERP_WindowsForms_Client.ServiceReference.GetRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRelativesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string empNo;
        
        public GetRelativesRequestBody() {
        }
        
        public GetRelativesRequestBody(string empNo) {
            this.empNo = empNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRelativesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetRelativesResponseBody Body;
        
        public GetRelativesResponse() {
        }
        
        public GetRelativesResponse(ERP_WindowsForms_Client.ServiceReference.GetRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.Relative[] GetRelativesResult;
        
        public GetRelativesResponseBody() {
        }
        
        public GetRelativesResponseBody(ERP_WindowsForms_Client.ServiceReference.Relative[] GetRelativesResult) {
            this.GetRelativesResult = GetRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.Employee emp;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(bool UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnNames", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequestBody Body;
        
        public GetColumnNamesRequest() {
        }
        
        public GetColumnNamesRequest(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetColumnNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetColumnNamesRequestBody() {
        }
        
        public GetColumnNamesRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetColumnNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetColumnNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponseBody Body;
        
        public GetColumnNamesResponse() {
        }
        
        public GetColumnNamesResponse(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetColumnNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetColumnNamesResult;
        
        public GetColumnNamesResponseBody() {
        }
        
        public GetColumnNamesResponseBody(ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetColumnNamesResult) {
            this.GetColumnNamesResult = GetColumnNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableNames", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequestBody Body;
        
        public GetTableNamesRequest() {
        }
        
        public GetTableNamesRequest(ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTableNamesRequestBody {
        
        public GetTableNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponseBody Body;
        
        public GetTableNamesResponse() {
        }
        
        public GetTableNamesResponse(ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTableNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetTableNamesResult;
        
        public GetTableNamesResponseBody() {
        }
        
        public GetTableNamesResponseBody(ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetTableNamesResult) {
            this.GetTableNamesResult = GetTableNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexes", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetIndexesRequestBody Body;
        
        public GetIndexesRequest() {
        }
        
        public GetIndexesRequest(ERP_WindowsForms_Client.ServiceReference.GetIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndexesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetIndexesRequestBody() {
        }
        
        public GetIndexesRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndexesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetIndexesResponseBody Body;
        
        public GetIndexesResponse() {
        }
        
        public GetIndexesResponse(ERP_WindowsForms_Client.ServiceReference.GetIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetIndexesResult;
        
        public GetIndexesResponseBody() {
        }
        
        public GetIndexesResponseBody(ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetIndexesResult) {
            this.GetIndexesResult = GetIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraints", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequestBody Body;
        
        public GetConstraintsRequest() {
        }
        
        public GetConstraintsRequest(ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConstraintsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetConstraintsRequestBody() {
        }
        
        public GetConstraintsRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConstraintsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponseBody Body;
        
        public GetConstraintsResponse() {
        }
        
        public GetConstraintsResponse(ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetConstraintsResult;
        
        public GetConstraintsResponseBody() {
        }
        
        public GetConstraintsResponseBody(ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetConstraintsResult) {
            this.GetConstraintsResult = GetConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeNameMostAbsenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeNameMostAbsence", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequestBody Body;
        
        public GetEmployeeNameMostAbsenceRequest() {
        }
        
        public GetEmployeeNameMostAbsenceRequest(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeNameMostAbsenceRequestBody {
        
        public GetEmployeeNameMostAbsenceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeNameMostAbsenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeNameMostAbsenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponseBody Body;
        
        public GetEmployeeNameMostAbsenceResponse() {
        }
        
        public GetEmployeeNameMostAbsenceResponse(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeNameMostAbsenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmployeeNameMostAbsenceResult;
        
        public GetEmployeeNameMostAbsenceResponseBody() {
        }
        
        public GetEmployeeNameMostAbsenceResponseBody(string GetEmployeeNameMostAbsenceResult) {
            this.GetEmployeeNameMostAbsenceResult = GetEmployeeNameMostAbsenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableContent", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetTableContentRequestBody Body;
        
        public GetTableContentRequest() {
        }
        
        public GetTableContentRequest(ERP_WindowsForms_Client.ServiceReference.GetTableContentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTableContentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tableName;
        
        public GetTableContentRequestBody() {
        }
        
        public GetTableContentRequestBody(string tableName) {
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableContentResponse", Namespace="http://tempuri.org/", Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.GetTableContentResponseBody Body;
        
        public GetTableContentResponse() {
        }
        
        public GetTableContentResponse(ERP_WindowsForms_Client.ServiceReference.GetTableContentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTableContentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString[] GetTableContentResult;
        
        public GetTableContentResponseBody() {
        }
        
        public GetTableContentResponseBody(ERP_WindowsForms_Client.ServiceReference.ArrayOfString[] GetTableContentResult) {
            this.GetTableContentResult = GetTableContentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CronusSoapChannel : ERP_WindowsForms_Client.ServiceReference.CronusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CronusSoapClient : System.ServiceModel.ClientBase<ERP_WindowsForms_Client.ServiceReference.CronusSoap>, ERP_WindowsForms_Client.ServiceReference.CronusSoap {
        
        public CronusSoapClient() {
        }
        
        public CronusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CronusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CronusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetEmployees(ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.Employee[] GetEmployees() {
            ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequestBody();
            ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetEmployeesAsync(ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeesResponse> GetEmployeesAsync() {
            ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetEmployeesRequestBody();
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.RemoveEmployee(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployee(request);
        }
        
        public bool RemoveEmployee(string no) {
            ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequestBody();
            inValue.Body.no = no;
            ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).RemoveEmployee(inValue);
            return retVal.Body.RemoveEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.RemoveEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeResponse> RemoveEmployeeAsync(string no) {
            ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.RemoveEmployeeRequestBody();
            inValue.Body.no = no;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).RemoveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.CreateEmployee(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public bool CreateEmployee(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequestBody();
            inValue.Body.emp = emp;
            ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.CreateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.CreateEmployeeResponse> CreateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.CreateEmployeeRequestBody();
            inValue.Body.emp = emp;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetSickEmployeesByYear(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest request) {
            return base.Channel.GetSickEmployeesByYear(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.Employee[] GetSickEmployeesByYear(string year) {
            ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequestBody();
            inValue.Body.year = year;
            ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetSickEmployeesByYear(inValue);
            return retVal.Body.GetSickEmployeesByYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetSickEmployeesByYearAsync(ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest request) {
            return base.Channel.GetSickEmployeesByYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearResponse> GetSickEmployeesByYearAsync(string year) {
            ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetSickEmployeesByYearRequestBody();
            inValue.Body.year = year;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetSickEmployeesByYearAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetRelatives(ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest request) {
            return base.Channel.GetRelatives(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.Relative[] GetRelatives(string empNo) {
            ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetRelativesRequestBody();
            inValue.Body.empNo = empNo;
            ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetRelatives(inValue);
            return retVal.Body.GetRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetRelativesAsync(ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest request) {
            return base.Channel.GetRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetRelativesResponse> GetRelativesAsync(string empNo) {
            ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetRelativesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetRelativesRequestBody();
            inValue.Body.empNo = empNo;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.UpdateEmployee(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public bool UpdateEmployee(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequestBody();
            inValue.Body.emp = emp;
            ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.UpdateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeResponse> UpdateEmployeeAsync(ERP_WindowsForms_Client.ServiceReference.Employee emp) {
            ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest inValue = new ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.UpdateEmployeeRequestBody();
            inValue.Body.emp = emp;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetColumnNames(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest request) {
            return base.Channel.GetColumnNames(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetColumnNames(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequestBody();
            inValue.Body.tableName = tableName;
            ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetColumnNames(inValue);
            return retVal.Body.GetColumnNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetColumnNamesAsync(ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest request) {
            return base.Channel.GetColumnNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetColumnNamesResponse> GetColumnNamesAsync(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetColumnNamesRequestBody();
            inValue.Body.tableName = tableName;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetColumnNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetTableNames(ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest request) {
            return base.Channel.GetTableNames(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString GetTableNames() {
            ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequestBody();
            ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetTableNames(inValue);
            return retVal.Body.GetTableNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetTableNamesAsync(ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest request) {
            return base.Channel.GetTableNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableNamesResponse> GetTableNamesAsync() {
            ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetTableNamesRequestBody();
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetTableNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetIndexes(ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest request) {
            return base.Channel.GetIndexes(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetIndexes(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetIndexesRequestBody();
            inValue.Body.tableName = tableName;
            ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetIndexes(inValue);
            return retVal.Body.GetIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetIndexesAsync(ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest request) {
            return base.Channel.GetIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetIndexesResponse> GetIndexesAsync(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetIndexesRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetIndexesRequestBody();
            inValue.Body.tableName = tableName;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetConstraints(ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest request) {
            return base.Channel.GetConstraints(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.MetadataItem[] GetConstraints(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequestBody();
            inValue.Body.tableName = tableName;
            ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetConstraints(inValue);
            return retVal.Body.GetConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetConstraintsAsync(ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest request) {
            return base.Channel.GetConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetConstraintsResponse> GetConstraintsAsync(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetConstraintsRequestBody();
            inValue.Body.tableName = tableName;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetEmployeeNameMostAbsence(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest request) {
            return base.Channel.GetEmployeeNameMostAbsence(request);
        }
        
        public string GetEmployeeNameMostAbsence() {
            ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequestBody();
            ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetEmployeeNameMostAbsence(inValue);
            return retVal.Body.GetEmployeeNameMostAbsenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetEmployeeNameMostAbsenceAsync(ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest request) {
            return base.Channel.GetEmployeeNameMostAbsenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceResponse> GetEmployeeNameMostAbsenceAsync() {
            ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetEmployeeNameMostAbsenceRequestBody();
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetEmployeeNameMostAbsenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetTableContent(ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest request) {
            return base.Channel.GetTableContent(request);
        }
        
        public ERP_WindowsForms_Client.ServiceReference.ArrayOfString[] GetTableContent(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetTableContentRequestBody();
            inValue.Body.tableName = tableName;
            ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse retVal = ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetTableContent(inValue);
            return retVal.Body.GetTableContentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse> ERP_WindowsForms_Client.ServiceReference.CronusSoap.GetTableContentAsync(ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest request) {
            return base.Channel.GetTableContentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERP_WindowsForms_Client.ServiceReference.GetTableContentResponse> GetTableContentAsync(string tableName) {
            ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest inValue = new ERP_WindowsForms_Client.ServiceReference.GetTableContentRequest();
            inValue.Body = new ERP_WindowsForms_Client.ServiceReference.GetTableContentRequestBody();
            inValue.Body.tableName = tableName;
            return ((ERP_WindowsForms_Client.ServiceReference.CronusSoap)(this)).GetTableContentAsync(inValue);
        }
    }
}
