//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS1_WindowsForms_Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ReadFileSoap")]
    public interface ReadFileSoap {
        
        // CODEGEN: Generating message contract since element name filePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenFile", ReplyAction="*")]
        WS1_WindowsForms_Client.ServiceReference.OpenFileResponse OpenFile(WS1_WindowsForms_Client.ServiceReference.OpenFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenFile", ReplyAction="*")]
        System.Threading.Tasks.Task<WS1_WindowsForms_Client.ServiceReference.OpenFileResponse> OpenFileAsync(WS1_WindowsForms_Client.ServiceReference.OpenFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenFile", Namespace="http://tempuri.org/", Order=0)]
        public WS1_WindowsForms_Client.ServiceReference.OpenFileRequestBody Body;
        
        public OpenFileRequest() {
        }
        
        public OpenFileRequest(WS1_WindowsForms_Client.ServiceReference.OpenFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        public OpenFileRequestBody() {
        }
        
        public OpenFileRequestBody(string filePath) {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS1_WindowsForms_Client.ServiceReference.OpenFileResponseBody Body;
        
        public OpenFileResponse() {
        }
        
        public OpenFileResponse(WS1_WindowsForms_Client.ServiceReference.OpenFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OpenFileResult;
        
        public OpenFileResponseBody() {
        }
        
        public OpenFileResponseBody(string OpenFileResult) {
            this.OpenFileResult = OpenFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReadFileSoapChannel : WS1_WindowsForms_Client.ServiceReference.ReadFileSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadFileSoapClient : System.ServiceModel.ClientBase<WS1_WindowsForms_Client.ServiceReference.ReadFileSoap>, WS1_WindowsForms_Client.ServiceReference.ReadFileSoap {
        
        public ReadFileSoapClient() {
        }
        
        public ReadFileSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReadFileSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadFileSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReadFileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS1_WindowsForms_Client.ServiceReference.OpenFileResponse WS1_WindowsForms_Client.ServiceReference.ReadFileSoap.OpenFile(WS1_WindowsForms_Client.ServiceReference.OpenFileRequest request) {
            return base.Channel.OpenFile(request);
        }
        
        public string OpenFile(string filePath) {
            WS1_WindowsForms_Client.ServiceReference.OpenFileRequest inValue = new WS1_WindowsForms_Client.ServiceReference.OpenFileRequest();
            inValue.Body = new WS1_WindowsForms_Client.ServiceReference.OpenFileRequestBody();
            inValue.Body.filePath = filePath;
            WS1_WindowsForms_Client.ServiceReference.OpenFileResponse retVal = ((WS1_WindowsForms_Client.ServiceReference.ReadFileSoap)(this)).OpenFile(inValue);
            return retVal.Body.OpenFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS1_WindowsForms_Client.ServiceReference.OpenFileResponse> WS1_WindowsForms_Client.ServiceReference.ReadFileSoap.OpenFileAsync(WS1_WindowsForms_Client.ServiceReference.OpenFileRequest request) {
            return base.Channel.OpenFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS1_WindowsForms_Client.ServiceReference.OpenFileResponse> OpenFileAsync(string filePath) {
            WS1_WindowsForms_Client.ServiceReference.OpenFileRequest inValue = new WS1_WindowsForms_Client.ServiceReference.OpenFileRequest();
            inValue.Body = new WS1_WindowsForms_Client.ServiceReference.OpenFileRequestBody();
            inValue.Body.filePath = filePath;
            return ((WS1_WindowsForms_Client.ServiceReference.ReadFileSoap)(this)).OpenFileAsync(inValue);
        }
    }
}
